database:
  user: connect
  password: password
  database: invoicesystem
  host: 127.0.0.1
website:
  view: App/Views
  routes: Routes
  controller: App/Controllers
  https: true
security:
  salt: test
  public:
  private:
